# This is a basic workflow to help you get started with Actions

# Sets the name of your GitHub Actions workflow.
name: singapore_air_quality_json

# get credentials from Github secrets
env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

# Controls when the workflow will run
on:
  schedule:
     - cron: '0 17 * * *'  # Runs daily at 1AM SGT
 # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # This step checks out my GitHub repo's code
      # into the runner so that it can access your files 
      - uses: actions/checkout@v3
      - run: |
          home_dir=$(pwd)
          echo $home_dir
          echo -----------------------------------------------------------------------
          pip install --upgrade pip    
          echo -----------------------------------------------------------------------
          pip install "snowflake-snowpark-python[pandas]"
          echo -----------------------------------------------------------------------
          ls -la
          pwd
          echo ----------------------------------------------------------------------- 
          python $home_dir/data-ingestion.py
      
      # The | is a YAML syntax called a block scalar. It means:
      #   - "Treat everything indented below as a multi-line string"
      #   - Each line is treated as a new line, as if you're writing a shell script

      # echo ------------- is just a visual separator, makes log output easier to read

      # python $home_dir/ingest-api-data.py -> basically means to 
      # “Run the Python script that lives in the root directory of my GitHub repo.”
